#!/usr/bin/env bash
# Start E5 search server with ALL custom datasets
#
# This script loads all datasets from the manifest file generated by
# generate_e5_embeddings.py, so you don't need to switch between datasets.
#
# Usage:
#   ./start_e5_with_custom_corpus.sh                    # Use default manifest
#   MANIFEST=/path/to/manifest.json ./start_e5_with_custom_corpus.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Configuration
CORPUS_BASE="${CORPUS_BASE:-$SCRIPT_DIR/data/custom_corpus}"
MANIFEST="${MANIFEST:-$CORPUS_BASE/manifest.json}"
MODEL="${MODEL:-intfloat/e5-large-v2}"
PORT="${PORT:-8090}"

echo "============================================"
echo "Starting E5 Server with Multiple Datasets"
echo "============================================"

# Check if manifest exists
if [ ! -f "$MANIFEST" ]; then
    echo "❌ Error: Manifest file not found: $MANIFEST"
    echo ""
    echo "You need to generate embeddings first:"
    echo "  python generate_e5_embeddings.py"
    echo ""
    echo "Or check that the corpus base directory is correct:"
    echo "  CORPUS_BASE=/path/to/corpus ./start_e5_with_custom_corpus.sh"
    echo ""
    exit 1
fi

# Parse manifest for info
if command -v python3 &> /dev/null; then
    MANIFEST_INFO=$(python3 -c "
import json
with open('$MANIFEST') as f:
    m = json.load(f)
print(f\"Datasets: {m['total_datasets']}\")
print(f\"Documents: {m['total_docs']}\")
for d in m['datasets']:
    print(f\"  - {d['name']}: {d['num_docs']} docs\")
")
    echo "$MANIFEST_INFO"
else
    echo "Manifest: $MANIFEST"
fi

echo ""
echo "Configuration:"
echo "  Manifest: $MANIFEST"
echo "  Model: $MODEL"
echo "  Port: $PORT"
echo ""

# Check if server already running
if nc -z localhost $PORT 2>/dev/null; then
    echo "⚠️  E5 server already running on port $PORT"
    echo ""
    echo "To restart, first kill the existing server:"
    echo "  pkill -f 'start_e5_custom.py'"
    echo ""
    exit 0
fi

# Start server
echo "🚀 Starting E5 server..."
cd "$SCRIPT_DIR"

PYTHONPATH=corag/src python corag/src/search/start_e5_custom.py \
    --manifest "$MANIFEST" \
    --model "$MODEL" \
    --port "$PORT" \
    > e5_custom_server.log 2>&1 &

SERVER_PID=$!

# Wait for server to start
echo "Waiting for server to start (PID: $SERVER_PID)..."
elapsed=0
while ! nc -z localhost $PORT 2>/dev/null; do
    sleep 2
    elapsed=$((elapsed + 2))
    if [ $elapsed -ge 120 ]; then
        echo "❌ Server did not start within 120 seconds"
        echo "Check logs: tail -f e5_custom_server.log"
        exit 1
    fi
    # Show progress
    if [ $((elapsed % 10)) -eq 0 ]; then
        echo "  Still waiting... ($elapsed seconds)"
    fi
done

# Test server
echo ""
echo "✅ E5 server started successfully!"
echo ""
echo "Testing server..."
HEALTH=$(curl -s http://localhost:$PORT/health)
echo "Health check: $HEALTH"

echo ""
echo "Testing search..."
curl -s -X POST http://localhost:$PORT/ \
    -H 'Content-Type: application/json' \
    -d '{"query":"test query","k":3}' | python3 -c "
import sys, json
results = json.load(sys.stdin)
print(f'Search returned {len(results)} results')
if results:
    print(f'  Top result from dataset: {results[0].get(\"_dataset\", \"unknown\")}')
"

echo ""
echo "============================================"
echo "✅ E5 Server Ready!"
echo "============================================"
echo "Server PID: $SERVER_PID"
echo "Logs: tail -f e5_custom_server.log"
echo ""
echo "Endpoints:"
echo "  Search: curl -X POST http://localhost:$PORT/ -H 'Content-Type: application/json' -d '{\"query\":\"your query\",\"k\":10}'"
echo "  Health: curl http://localhost:$PORT/health"
echo "  Datasets: curl http://localhost:$PORT/datasets"
echo ""
echo "Filter by dataset:"
echo "  curl -X POST http://localhost:$PORT/ -H 'Content-Type: application/json' -d '{\"query\":\"your query\",\"k\":10,\"dataset\":\"scifact\"}'"
echo ""
echo "Now you can:"
echo "1. Start vLLM: cd corag && bash scripts/start_vllm_server.sh"
echo "2. Run CoRAG: python cli.py --config configs_3b/your_config.yaml"
echo "============================================"
