system:
  name: ratllm
  alpha: 0.1
  args:
    model_name: meta-llama/Llama-3.2-3B-Instruct
    method: attack

dataset: datasets/commit_message_qa.json
output: results/ratllm/attack/llama_3.2_3b_instruct/commit_message_qa_0.1
