system:
  name: ratrag
  alpha: 0.1
  args:
    model_name: meta-llama/Llama-3.2-3B-Instruct
    method: normal

dataset: datasets/OlympiadBench.json
output: results/ratrag/normal/llama_3.2_3b_instruct/olympiadbench_0.1
