system:
  name: ratrag
  alpha: 0.1
  args:
    model_name: meta-llama/Llama-3.2-3B-Instruct
    method: aware

dataset: datasets/multinewsum_mcqa.json
output: results/ratrag/aware/llama_3.2_3b_instruct/multinewsum_mcqa_0.1
