system:
  name: replugrag
  alpha: 0.1
  args:
    model_name: meta-llama/Llama-3.2-3B-Instruct
    method: normal

dataset: datasets/commit_message_qa.json
output: results/replugrag/normal/llama_3.2_3b_instruct/commit_message_qa_0.1
