system:
  name: replugllm
  alpha: 0.1
  args:
    model_name: meta-llama/Llama-3.2-3B-Instruct
    method: attack

dataset: datasets/odex.json
output: results/replugllm/attack/llama_3.2_3b_instruct/odex_0.1
