system:
  name: selfrag
  alpha: 0.1
  args:
    model_name: meta-llama/Llama-3.2-3B-Instruct
    method: attack

dataset: datasets/dialfact.json
output: results/selfrag/attack/llama_3.2_3b_instruct/dialfact_0.1
