system:
  name: simplellm
  alpha: 0.1
  args:
    model_name: meta-llama/Llama-3.1-8B-Instruct
    method: aware

dataset: datasets/odex.json
output: results/simplellm_aware_meta-llama/Llama-3.1-8B-Instruct_odex_0.1
