system:
  name: simplerag
  alpha: 0.1
  args:
    model_name: meta-llama/Llama-3.1-8B-Instruct

dataset: datasets/crag_task_1_and_2_mcqa_example.json
output: results/simplerag_llama_3.1_8b_instruct_crag_task_1_and_2_mcqa_example
