system:
  name: simplerag
  alpha: 0.1
  args:
    model_name: meta-llama/Llama-3.2-3B-Instruct
    method: attack

dataset: datasets/healthver_mcqa.json
output: results/simplerag/attack/llama_3.2_3b_instruct/healthver_mcqa_0.1
