system:
  name: simplerag
  alpha: 0.1
  args:
    model_name: meta-llama/Llama-3.1-8B-Instruct
    method: aware

dataset: datasets/dialfact.json
output: results/simplerag_aware_meta-llama/Llama-3.1-8B-Instruct_dialfact_0.1
