from systems.abstract import AbstractRAGSystem
from systems.simplellm import SimpleLLMSystem, SYSTEM_PROMPT
from typing import Dict, Any, List
from utils.clean import clean_web_content
from utils.ramdb import ChunkSearcher
from utils.storage import get_storage
import torch
# from utils.vllm_client import LLMClient

# step 1
def generate_subquery_prompt(is_parser: bool = False, query: str = None, past_subqueries: List[str] = None, past_subanswers: List[str] = None) -> str:
    if is_parser:
        def parser(x):
            return x[:500]
        return parser
    else:
        past = ''
        for idx in range(len(past_subqueries)):
            past += f"""Intermediate query {idx+1}: {past_subqueries[idx]}
    Intermediate answer {idx + 1}: {past_subanswers[idx]}\n"""
        past = past.strip()
        return f"""You are using a search engine to answer the main query by iteratively searching the web. Given the following intermediate queries and answers, generate a new simple follow-up question that can help answer the main query. You may rephrase or decompose the main query when previous answers are not helpful. Ask simple follow-up questions only as the search engine may not understand complex questions.

## Previous intermediate queries and answers
{past or 'Nothing yet'}

## Main query to answer
{query}

Respond with a simple follow-up question that will help answer the main query, do not explain yourself or output anything else."""

# step 3
def get_generate_intermediate_answer_prompt(is_parser: bool = False, subquery: str = None, documents: List[str] = None) -> str:
    if is_parser:
        def parser(x):
            return x[:500]
        return parser
    else:
        context = ''
        for idx, doc in enumerate(documents):
            context += f"""{doc}\n\n"""

        return f"""Given the following documents, generate an appropriate answer for the query. DO NOT hallucinate any information, only use the provided documents to generate the answer. Respond "No relevant information found" if the documents do not contain useful information.

## Documents
{context.strip()}

## Query
{subquery}

Respond with a concise answer only, do not explain yourself or output anything else."""

def generate_final_answer_prompt(is_parser: bool = False, past_subqueries: List[str] = None, past_subanswers: List[str] = None, documents: List[str] = None) -> str:
    if is_parser:
        def parser(x):
            return x[:500]
        return parser
    else:
        past = ''
        for idx in range(len(past_subqueries)):
            past += f"""Intermediate query {idx+1}: {past_subqueries[idx]}
Intermediate answer {idx+1}: {past_subanswers[idx]}\n"""
        past = past.strip()

        context = ''
        if documents:
            for idx, doc in enumerate(documents[::-1]):
                context = f"""Doc {idx}: {doc}\n\n""" + context
                if len(context) > 5000:
                    break
        return f"""Given the following intermediate queries and answers, generate a final answer for the main query by combining relevant information. Note that intermediate answers are generated by an LLM and may not always be accurate.

## Documents
{context.strip()}

## Intermediate queries and answers
{past or 'Nothing yet'}
"""

class CoRAGSystem(AbstractRAGSystem):    
    def __init__(self, model_name: str = "meta-llama/Llama-3.1-8B-Instruct", device: str = "cuda", retrieved_docs: int = 10, L: int = 3, **kwargs):
        self.retrieved_docs = retrieved_docs
        self.llm_system = SimpleLLMSystem(model_name, device=device, technique='rag', **kwargs)
        self.embedding_model = "all-MiniLM-L6-v2"
        self.L = L
    
    def get_batch_size(self) -> int: return 8
    
    def _generate_prompt(self, question) -> str:
        try:
            prompt = self.llm_system.tokenizer.apply_chat_template([
                {"role": "system", "content": "You are a helpful assistant that generates answer shortly and concisely."},
                {"role": "user", "content": question}
                ], tokenize=False, add_generation_prompt=True)
        except: pass

        return prompt

    def _generate_answer(self, questions: List[str]) -> List[str]:
        prompt = [self._generate_prompt(question) for question in questions]
        # Lấy device từ model (cần thiết khi dùng device_map='auto')
        device = getattr(self.llm_system.model, "device", next(self.llm_system.model.parameters()).device)
        inputs = self.llm_system.tokenizer(prompt, return_tensors="pt", padding=True, truncation=True).to(device)
        with torch.no_grad():
            outputs = self.llm_system.model.generate(
                **inputs,
                max_new_tokens=self.llm_system.max_new_tokens,
                temperature=self.llm_system.temperature,
                do_sample=True,
                pad_token_id=self.llm_system.tokenizer.eos_token_id,
                return_dict_in_generate=True,
            )

        generated_texts = []
        for i in range(len(questions)):
            generated_text = self.llm_system.tokenizer.decode(outputs.sequences[i], skip_special_tokens=True).split('assistant\n\n')[-1]
            generated_texts.append(generated_text)

        return generated_texts
    
    def batch_process_samples(self, samples: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        embedding_model = "all-MiniLM-L6-v2"
        sample = samples[0]
        if sample.get('search_results', []) != [] and \
            sample['search_results'][0].get('persistent_storage', None):
            if not hasattr(self, 'database'):
                self.database = ChunkSearcher(embedding_model=embedding_model)
                self.database.set_documents([get_storage(sample['search_results'][0]['persistent_storage'])])
            database = self.database
        else:
            documents = [[doc['page_snippet'] + "\n\n" + clean_web_content(doc.get('page_result', ''))
                        for doc in _sample.get('search_results', [])] for _sample in samples]
            database = ChunkSearcher(embedding_model=embedding_model)
            database.set_documents(documents)

        past_subqueries = []
        past_subanswers = []
        past_documents = []

        subqueries_parser = generate_subquery_prompt(is_parser=True)
        intermediate_answer_parser = get_generate_intermediate_answer_prompt(is_parser=True)
        for _ in range(self.L):
            # get prompt for subquery generation
            subquery_prompt = [generate_subquery_prompt(is_parser=False, query=sample.get('question', ''), 
            past_subqueries=[_subquery[idx] for _subquery in past_subqueries],
            past_subanswers=[_subanswer[idx] for _subanswer in past_subanswers]) for idx, sample in enumerate(samples)]
            subquery_prompt = [{i} for i in subquery_prompt]
            subqueries = self._generate_answer(subquery_prompt)
            subqueries = [subqueries_parser(subquery.split('assistant\n\n')[-1]) for subquery in subqueries]
            past_subqueries.append(subqueries)

            # search for documents from subqueries
            retrieved_docs = database.batch_search(
                [sample.get('question', '') for sample in samples],
                [i for i in range(len(samples))],
                k=self.retrieved_docs)
            past_documents.append(retrieved_docs)

            # answer the subquery
            answer_prompt = [get_generate_intermediate_answer_prompt(
                is_parser=False, subquery=subquery,
                documents=[retrieved_doc]
                ) for subquery, retrieved_doc in zip(subqueries, retrieved_docs)]
            intermediate_answers = self._generate_answer(answer_prompt)
            intermediate_answers = [intermediate_answer_parser(answer.split('assistant\n\n')[-1]) for answer in intermediate_answers]
            past_subanswers.append(intermediate_answers)

        final_answer_contexts = [generate_final_answer_prompt(
            is_parser=False,
            past_subqueries=[_subquery[idx] for _subquery in past_subqueries],
            past_subanswers=[_subanswer[idx] for _subanswer in past_subanswers],
            documents=[past_doc[idx] for past_doc in past_documents]
            ) for idx in range(len(samples))]
        # Gắn context vào từng sample giống simplerag: augmented_sample['context'] = ...
        # SimpleLLMSystem(technique='rag') dùng sample.get('context', '') trong _generate_prompt
        augmented_samples = []
        for sample, context_str in zip(samples, final_answer_contexts):
            augmented_sample = sample.copy()
            augmented_sample["context"] = context_str
            augmented_samples.append(augmented_sample)
        final_answers = self.llm_system.batch_process_samples(augmented_samples)

        return final_answers
